[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
description = "A fast and limited-memory structure with a landmask based on GSHHG for determing whether a point on Earth is on land or in the ocean"
name = "roaring-landmask"
version = "0.2.1"
edition = "2018"
license = "MIT"
homepage = "https://github.com/gauteh/roaring-landmask"
repository = "https://github.com/gauteh/roaring-landmask"
exclude = [ "gshhs/*" ]

[lib]
name = "roaring_landmask"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "make_bitmap"
path = "src/devel/make_bitmap.rs"

[[bin]]
name = "rasterize"
path = "src/devel/rasterize.rs"

[[bin]]
name = "rasterize2"
path = "src/devel/rasterize2.rs"

[dependencies]
geos = "8.0.1"
lazy_static = "1.4.0"
numpy = "0.13.1"
pyo3 = "0.13.2"
roaring = "0.7.0"
rust-embed = "5.9.0"
xz2 = "0.1.6"
rayon = "*"

[build-dependencies]
reqwest = { version = "0.11", features = [ "blocking" ] }
ring = "0.16"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[profile.release]
debug = true

